include:
  - project: 'ece651proj/ci-templates'
    file: 
        - 'stages.yml'
        - 'build_jobs.yml'

sanity_build:   
    extends: .sanity_build

image_build:
    tags:
      - ece651
    image: docker  
    stage: build
    script:
      - apk update && apk add gettext
      - envsubst < .env > ./config && mv ./config .env
      - docker login -u $DOCKERUSER -p $DOCKERPUSHER
      - |
        if [[ -f ./Dockerfile ]]
        then 
          docker build -t $DOCKERHUB/${CI_PROJECT_NAME}:$CI_PIPELINE_IID .
          docker push $DOCKERHUB/${CI_PROJECT_NAME}:$CI_PIPELINE_IID
        else
          echo "Dockerfile not found, please add docker file"
          exit 1
        fi

Test:
  tags:
    - ece651
  image: node:19-alpine3.16
  stage: test
  script:
    - npm install
    - npm test
    - cd coverage
    - ls -al 
  artifacts:
    paths:
      - coverage/
  allow_failure: true

Coverage:
  tags:
    - ece651
  image: sonarsource/sonar-scanner-cli
  stage: posttest
  script:
    - ls -al
    - apk update && apk add gettext
    - export tag=$(awk '/version/{print $2; exit;}' package.json | cut -d '"' -f 2)
    - envsubst < sonar-project.properties > ./config && mv ./config sonar-project.properties
    - sonar-scanner
  allow_failure: true

deploy:
    tags:
      - ece651
    image: docker  
    stage: deploy
    script:
      - apk update && apk add gettext
      - envsubst < ./docker-compose.yml > ./config && mv ./config .docker-compose.yml
      - docker-compose pull
      - docker-compose up -d
    rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: always
