
exports.responseMessages = {
    MISSING_REQUIRED_FIELDS : "MISSING_REQUIRED_FIELDS",
    REGISTRATION_SUCCESS    : "REGISTRATION_SUCCESS",
    LOGIN_SUCCESS           : "LOGIN_SUCCESS",
    ALREADY_REGISTERED      : "ALREADY_REGISTERED",
    FAIL_REGISTERED         : "FAIL_REGISTERED",
    SUCCESS_REGISTERED      : "SUCCESS_REGISTERED",
    FAIL_LOGIN              : "FAIL_LOGIN",
    SUCCESS_LOGIN           : "SUCCESS_LOGIN",
    USER_NOT_FOUND          : "USER_NOT_FOUND",
    WRONG_CREDENTIALS       : "WRONG_CREDENTIALS",
    UNAUTHORISED            : "UNAUTHORISED",
    SUCCESS                 : "SUCCESS",
    FAILURE                 : "FAILURE"
}
